### ISSUE TITLE
Not working for me!

### ISSUE THREAD

**Issue by akhil-mysore** [seebi/tmux-colors-solarized#7]
I am new to Mac and tmux. Please be gentle :)

I am using Mac, iterm2. I double checked my config file and also made sure tmux is using the config file. Can you please help me with this? What do you suggest me to debug ? Please let me know if you need more info to fix this.

Thanks,

**Comment by breerly** [comment]
Can you describe what exactly is not working?

**Comment by jbcpollak** [comment]
If anyone else comes across this, I can't explain exactly what it took, but a combination of restarting tmux and reloading the config finally made the config work for me. Keep in mind this just themes tmux itself - changing the colors of your terminal's text is up to you

**Comment by bobismijnnaam** [comment]
For completeness, jbcpollak's comment made it click for me, and with the help of this page (https://sanctum.geek.nz/arabesque/reloading-tmux-config/) I got the scheme to work. In short, restarting tmux/reloading your config entails pressing the tmux key combination (Ctrl+A for me, Ctrl+B by default) and entering the following line:

```
:source-file ~/.tmux.conf
```

Or as a regular command:

```
$ tmux source-file ~/.tmux.conf
```

If that doesn't work (warning, this will close your terminal!):

```
$ tmux kill-server
```

And then starting tmux again.
