### ISSUE TITLE
status bell style is missing

### ISSUE THREAD

**Issue by r8b7xy** [seebi/tmux-colors-solarized#8]
This is my proposition for missing status bell style:
```
set-window-option -g window-status-bell-style fg=brightblack,bg=red
```
I'm using dark theme right now - it can be adjusted for other color variants as well.

**Comment by seebi** [comment]
pull request pls

**Comment by seebi** [comment]
added in https://github.com/seebi/tmux-colors-solarized/commit/60d096df3cb2706709b7d0eb5270e48a8316e5da
