### ISSUE TITLE
Install as tpm-plugin

### ISSUE THREAD

**Issue by breerly** [seebi/tmux-colors-solarized#9]
Would love not to manually copy paste this source, and instead use:

https://github.com/tmux-plugins/tpm

**Comment by bruno-** [comment]
@breerly pinged me on twitter so I implemented this functionality in #10.

@breerly, it would be great if you could confirm this works for you too. Until the PR gets merged you can install the plugin with:

    set -g @plugin 'bruno-/tmux-colors-solarized'

Just the default theme works for now. We can easily implement the support for dark/light theme, but let's wait to see if the owner likes this idea at all.

**Comment by breerly** [comment]
@bruno- I think it worked:
![screen shot 2015-07-28 at 9 52 50 am](https://cloud.githubusercontent.com/assets/263587/8937579/6acb1440-350e-11e5-9b32-336e11de76e8.png)

**Comment by breerly** [comment]
Looks a bit more brown than blue though...

**Comment by breerly** [comment]
:+1:

**Comment by bruno-** [comment]
All right, this is merged. :tada:

**Comment by breerly** [comment]
@bruno nice! :beers: 

How do you think we should go about enabling the other themes? there's:

```
tmuxcolors-256.conf
tmuxcolors-dark.conf
tmuxcolors-light.conf
```

**Comment by bruno-** [comment]
@breerly, I submitted a PR for this here: #11
